import { ExportPayload } from './types';
import { RoundTelemetry, AgentEpidemicState } from '../simulation/types';

function threatLevel(r0: number): { label: string; color: string } {
  if (r0 >= 3) return { label: 'CRITICAL', color: '#ef4444' };
  if (r0 >= 2) return { label: 'HIGH', color: '#f97316' };
  if (r0 >= 1) return { label: 'MODERATE', color: '#eab308' };
  return { label: 'LOW', color: '#22c55e' };
}

function peakR0(history: RoundTelemetry[]): number {
  return Math.max(0, ...history.map((t) => t.r0));
}

export function exportToPDF(payload: ExportPayload): void {
  const { society, simState, telemetryHistory, discoveryReport } = payload;
  const r0 = peakR0(telemetryHistory);
  const threat = threatLevel(r0);

  const stateValues: AgentEpidemicState[] = Array.from(simState.agentStates.values());
  const totalBelievers = stateValues.filter((s) => s === 'BELIEVER').length;
  const totalSkeptics = stateValues.filter((s) => s === 'SKEPTIC').length;

  // DiscoveryReport uses hypothesisCards[] and intervention (single object)
  const topPattern =
    discoveryReport?.hypothesisCards?.[0]?.title ?? 'No patterns detected';
  const intervention =
    discoveryReport?.intervention?.expectedImpact ?? 'No recommendation';

  const timelineRows = telemetryHistory
    .slice(-20)
    .map(
      (t) => `
    <tr>
      <td>Round ${t.round}</td>
      <td>${t.believerCount}</td>
      <td>${t.skepticCount}</td>
      <td>${t.r0.toFixed(2)}</td>
      <td>${t.newInfections}</td>
    </tr>`
    )
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Social Gravity \u2014 Intelligence Brief \u2014 ${new Date(payload.exportedAt).toLocaleDateString()}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11pt; color: #1a1a2e; background: #fff; padding: 20mm; }
  h1 { font-size: 18pt; color: #0f3460; border-bottom: 2px solid #0f3460; padding-bottom: 6px; margin-bottom: 12px; }
  h2 { font-size: 13pt; color: #16213e; margin-top: 20px; margin-bottom: 8px; border-left: 4px solid #0f3460; padding-left: 8px; }
  .meta { font-size: 9pt; color: #555; margin-bottom: 16px; }
  .threat-badge { display: inline-block; padding: 4px 14px; border-radius: 4px; font-weight: bold; font-size: 12pt; color: #fff; background: ${threat.color}; }
  .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 12px 0; }
  .kpi { background: #f0f4ff; border-radius: 6px; padding: 10px 14px; }
  .kpi-value { font-size: 22pt; font-weight: 700; color: #0f3460; }
  .kpi-label { font-size: 8pt; color: #555; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; font-size: 9.5pt; margin-top: 8px; }
  th { background: #0f3460; color: #fff; padding: 6px 8px; text-align: left; }
  td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f9fafb; }
  .footer { margin-top: 30px; font-size: 8pt; color: #aaa; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 8px; }
  @media print { body { padding: 10mm; } }
</style>
</head>
<body>
<h1>&#128752; Social Gravity \u2014 Intelligence Brief</h1>
<div class="meta">
  Society: <strong>${society.name}</strong> &nbsp;|&nbsp;
  Agents: <strong>${society.agents.length}</strong> &nbsp;|&nbsp;
  Rounds: <strong>${simState.currentRound}</strong> &nbsp;|&nbsp;
  Generated: <strong>${new Date(payload.exportedAt).toLocaleString()}</strong>
</div>

<h2>Threat Assessment</h2>
<div class="threat-badge">${threat.label}</div>
<div class="kpi-grid" style="margin-top:12px">
  <div class="kpi"><div class="kpi-value">${r0.toFixed(2)}</div><div class="kpi-label">Peak R&#8320;</div></div>
  <div class="kpi"><div class="kpi-value">${totalBelievers}</div><div class="kpi-label">Believers</div></div>
  <div class="kpi"><div class="kpi-value">${totalSkeptics}</div><div class="kpi-label">Skeptics</div></div>
  <div class="kpi"><div class="kpi-value">${society.communities?.length ?? 0}</div><div class="kpi-label">Communities</div></div>
</div>

<h2>Top Detected Pattern</h2>
<p>${topPattern}</p>

<h2>Recommended Intervention</h2>
<p>${intervention}</p>

<h2>Cascade Timeline (last 20 rounds)</h2>
<table>
  <thead><tr><th>Round</th><th>Believers</th><th>Skeptics</th><th>R&#8320;</th><th>New Infections</th></tr></thead>
  <tbody>${timelineRows}</tbody>
</table>

<div class="footer">Generated by Social Gravity Decision Intelligence Platform &mdash; CONFIDENTIAL &mdash; ${payload.exportedAt}</div>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) {
    alert('Allow popups to generate PDF');
    return;
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
  }, 500);
}
